eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.0.138:8761/eureka}
  instance:
    hostname: 192.168.0.138
    instance-id: 192.168.0.138:${server.port}
  healthcheck :
    enabled : true
spring:
  cloud:
    config:
      override-system-properties: false
api:
  version : v01
services:
  cdn:
    baseUrl: "http://192.168.0.138:8085/cdn/v1.0"
  fgaccess:
    baseUrl: "http://localhost:8084/access/v1.0"
  notification:
    baseUrl: "http://localhost:8088/io.notification/v1.0"
  payment:
    baseUrl: "http://localhost:location:8083"
  report:
    baseUrl: "http://localhost:8086/report/v1.0"
  state:
    baseUrl: "http://localhost:8087/state/v1.0"