eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.0.138:8761/eureka}
  instance:
    hostname: 192.168.0.138
    instance-id: 192.168.0.138:${server.port}
  healthcheck :
    enabled : true
spring:
  cloud:
    config:
      override-system-properties: false
api:
  version : v01
services:
  cdn:
    baseUrl: "location:8085"
  fgaccess:
    baseUrl: "location:8084"
  notification:
    baseUrl: "location:8088"
  payment:
    baseUrl: ""
  report:
    baseUrl: "location:8086"
  state:
    baseUrl: "location:8087"