server:
  port: ${SERVER_PORT:8084}
spring:
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://192.168.0.138:5432/IO_FGACCESS_DB}
    username: ${R2DBC_USERNAME:postgres}
    password: ${R2DBC_PASSWORD:postgres}
    properties:
      logging.level: ${R2DBC_LOG_LEVEL:DEBUG}
  flyway:
    enabled: true
    url: ${FLYWAY_URL:jdbc:postgresql://192.168.0.138:5432/IO_FGACCESS_DB}
    user: ${FLYWAY_USERNAME:postgres}
    password: ${FLYWAY_PASSWORD:postgres}
    locations: ${FLYWAY_LOCATION:classpath:db/migration}

application:
  name: fgaccess
service:
  name: access
  apiversion: v1.0

logging:
  level:
    org.springframework.r2dbc: ${SERVICE_LOG_LEVEL:DEBUG}