server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: route_to_report
          uri: "lb://REPORT"
          predicates:
            - Path=/report/**

        - id: route_to_cdn
          uri: "lb://IO.CDN"
          predicates:
            - Path=/io.cdn/**


        - id: route_to_account
          uri: "lb://ACCOUNTS"
          predicates:
            - Path=/accounts/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://192.168.0.138:9090/realms/microservice-io"
#            ${OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI:http://192.168.0.138:9090/realms/microservice-io}
logging:
  level:
    org:
      springframework:
        security: TRACE