server:
  port: 8089
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.0.138:9092
      group-id: groupid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable.auto.commit: false
      properties:
#        schema.registry.url: http://localhost:${server.port}
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: kafkaRequestMessage:com.roconmachine.io.notification.processor.schema.MessageRequest

  mail:
    host: localhost
    port: 1025
    username: demo
    password: demo1@3
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

service:
  name: io.notification.processor
  apiversion: v1.0
  notification-kafka-topic: "email-topic"

