server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://192.168.0.138:5432/REPORT_DB
    username: postgres
    password: postgres

  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

service:
  name: report
  apiversion: v1.0